version: "3"
services:
  web:
    image: hseeberger/scala-sbt:8u222_1.3.5_2.13.1
    container_name: play-framework
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/root
    expose: 
      - "9000"
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_DATABASE: playdb
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./db/data:/var/lib/mysql
        - ./db/sql:/docker-entrypoint-initdb.d
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
        - "3314:3306"
    expose:
        - "3306"

      